services:
  dns:
    container_name: dns-adphantom
    build:
      context: ../../
      dockerfile: deployments/docker/dns/Dockerfile
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ../../configs:/app/configs
      - ../../logs:/app/logs

networks:
  app_net:
    name: AddPhantomNet
    driver: bridge
